

seed_everything: 7
trainer:
   logger:
     class_path: pytorch_lightning.loggers.WandbLogger
     init_args:
        project: "face_incertainty_train"
  log_every_n_steps: 3
  default_root_dir: outputs/scf_train
  enable_checkpointing: true
  callbacks:
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args: 
      every_n_train_steps: 1000
      dirpath: outputs/scf_train/weights
  - class_path: pytorch_lightning.callbacks.LearningRateMonitor
    init_args: 
      logging_interval: "step"
  - class_path: face_lib.models.scf.Prediction_writer
    init_args: 
      output_dir: /app/cache/features
      file_name: scf_embs_nose # scf_embs_inter  #scf_embs_lfw #scf_embs_ms1m_3531-classes_0-seed_30-min-class-size
      write_interval: epoch
  max_epochs: 5
  accelerator: gpu
  devices: 2
model:
    class_path: face_lib.models.scf.SphereConfidenceFace
    init_args:
        backbone:
            class_path: face_lib.models.lightning_wrappers.ResNet
            init_args:
                resnet_name: iresnet50_normalized
                weights: /app/model_weights/backbone/ms1mv3_arcface_r50/backbone.pth
                learnable: False
        head:
            class_path: face_lib.models.heads.SCFHead
            init_args:
                convf_dim: 25088
                latent_vector_size: 2048
        scf_loss:
            class_path: face_lib.models.losses.KLDiracPS
            init_args:
                z_dim: 512
                #radius: 64
        softmax_weights:
            class_path: face_lib.models.scf.SoftmaxWeights
            init_args:
                softmax_weights_path: /app/model_weights/backbone/ms1mv3_arcface_r50/softmax_weight.pt
                radius: 64 #${model.scf_loss.init_args.radius}
        optimizer_params:
            optimizer: AdamW # Adam
            params:
                lr: 1e-3
                weight_decay: 5e-3
        # scheduler_params:
        #     scheduler: CyclicLR
        #     params:
        #         base_lr: 3e-8
        #         max_lr: 3e-5
        #         step_size_up: 1000
        #         cycle_momentum: False
        #         mode: "triangular2"
        #     interval: "step"
        #     frequency: 1
        scheduler_params:
            scheduler: StepLR
            params:
                step_size: 5000
                gamma: 0.5
            interval: "step"
            frequency: 1
        permute_batch: False


data:
    class_path: face_lib.dataset_classes.lightning_datasets.UncertaintyDataModule
    init_args:
        data_train_dir: /app/datasets/ms1m/
        # predict_dataset:
        #     class_path: face_lib.dataset_classes.lightning_datasets.MXFaceDataset
        #     init_args: 
        #         root_dir: /app/datasets/ms1m/
        #         test: True
        #         num_classes: 3531
        predict_dataset:
            class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
            init_args:
                dataset_path: /app/datasets/gaussian_nose
                dataset_name: nose
                norm_image: True
        # predict_dataset:
        #     class_path: face_lib.dataset_classes.arcface_ijb.IJB_aligned_images
        #     init_args:
        #         dataset_path: /app/datasets/interpolation
        #         dataset_name: inter
        #         norm_image: True
        # predict_dataset:
        #     class_path: face_lib.dataset_classes.lfw.LFW_aligned_images
        #     init_args:
        #         dataset_path: /app/datasets/lfw/data_aligned_112_112
                #norm_image: True
        # predict_dataset:
        #     class_path: face_lib.datasets.arcface_ijb.IJB_aligned_images
        #     init_args:
        #         dataset_path: /app/datasets/arcface_ijb/IJBC
        #         dataset_name: IJBC
        #         norm_image: True

        # predict_dataset:
        #     class_path: face_lib.datasets.arcface_ijb.IJB_aligned_images
        #     init_args:
        #         dataset_path: /app/datasets/arcface_ijb/IJBC
        #         dataset_name: IJBC
        #         norm_image: True
        # predict_dataset:
        #     class_path: face_lib.datasets.qmul.SurvFace
        #     init_args:
        #         data_dir: /app/datasets/QMUL-SurvFace/Face_Identification_Test_Set

        batch_size: 9
        num_workers: 20